In [13]:
import pandas as pd

In [25]:
df = pd.read_csv('nyc_311.csv')

#renames zip codes to be one word
df = df.rename(columns={"Zip Codes" : "Zipcodes"})

df['Created Date'] = pd.to_datetime(df['Created Date'])

df['Date'] = df['Created Date'].dt.date

df['Time'] = df['Created Date'].dt.time

df = df.drop('Created Date', axis =1)

df

,Unique Key,Complaint Type,Descriptor,Location Type,Zipcodes,Date,Time
0,35137497,Derelict Vehicle,With License Plate,Street/Sidewalk,11729.0,2016-12-31,23:58:26
1,35136949,Noise - Residential,Loud Music/Party,Residential Building/House,13098.0,2016-12-31,23:56:41
2,35140076,Noise - Residential,Loud Talking,Residential Building/House,12075.0,2016-12-31,23:56:34
3,35138375,Noise - Residential,Loud Music/Party,Residential Building/House,13090.0,2016-12-31,23:55:01
4,35141923,Homeless Person Assistance,NaN,Street/Sidewalk,12079.0,2016-12-31,23:54:55
...,...,...,...,...,...,...,...
527951,32311692,Rodent,Rat Sighting,3+ Family Apt. Building,12426.0,2016-01-01,00:00:00
527952,32312944,Rodent,Rat Sighting,Catch Basin/Sewer,12423.0,2016-01-01,00:00:00
527953,32312027,Rodent,Rat Sighting,3+ Family Apt. Building,12428.0,2016-01-01,00:00:00
527954,32310860,Rodent,Rat Sighting,3+ Family Apt. Building,10099.0,2016-01-01,00:00:00
527955,32310788,Rodent,Mouse Sighting,3+ Family Apt. Building,12426.0,2016-01-01,00:00:00

In [33]:
#specifies zip codes to manhattan only
df = df[df.notnull().all(axis = 1)]
df = df[df['Zipcodes'] > 10000]
df = df[df['Zipcodes'] < 10283]
df

,Unique Key,Complaint Type,Descriptor,Location Type,Zipcodes,Date,Time
7,35136925,Noise - Residential,Loud Talking,Residential Building/House,10099.0,2016-12-31,23:50:22
50,35138249,PLUMBING,TOILET,RESIDENTIAL BUILDING,10092.0,2016-12-31,22:57:20
71,35144530,Dirty Conditions,E1 Improper Disposal,Sidewalk,10099.0,2016-12-31,22:36:00
141,35143099,Noise - Residential,Loud Music/Party,Residential Building/House,10099.0,2016-12-31,20:46:38
160,35144027,Dirty Conditions,E2 Receptacle Violation,Sidewalk,10099.0,2016-12-31,20:17:00
...,...,...,...,...,...,...,...
527834,32305290,Noise - Residential,Loud Music/Party,Residential Building/House,10099.0,2016-01-01,01:33:35
527883,32305292,Noise - Residential,Loud Music/Party,Residential Building/House,10099.0,2016-01-01,01:02:10
527899,32306018,Noise - Residential,Loud Music/Party,Residential Building/House,10099.0,2016-01-01,00:54:29
527940,32310278,Noise - Residential,Loud Music/Party,Residential Building/House,10099.0,2016-01-01,00:05:19
527954,32310860,Rodent,Rat Sighting,3+ Family Apt. Building,10099.0,2016-01-01,00:00:00

In [34]:
df.to_csv("final_311.csv")